### ISSUE TITLE
"CUDA error: invalid resource handle" on Standalone Training

### ISSUE THREAD

**Issue by HyeonchanKim** [petuum/adaptdl#100]
There was a runtime error "CUDA error: invalid resource handle" when I run "mnist_step_5.py".
https://github.com/petuum/adaptdl/blob/master/tutorial/mnist_step_5.py

I would really appreciate it if you answer on how to solve this problem.

### Error message

```
WARNING:adaptdl.reducer:Could not connect to root, trying again...
INFO:adaptdl.reducer:Master waiting for connections on 0
INFO:adaptdl.reducer:rank 0 connecting to 0.0.0.0 on port 47237
INFO:adaptdl.torch:Initializing torch.distributed using tcp://0.0.0.0:18068?rank=0&world_size=1
INFO:adaptdl.torch:torch.distributed initialized
/home/intern/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py:363: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES.
  warnings.warn(
INFO:adaptdl.torch.epoch:starting at epoch 0
Train Epoch: 0 [0/60000 (0%)]   Loss: 2.333050
Train Epoch: 0 [640/60000 (1%)] Loss: 1.686436
...
...
...
Train Epoch: 0 [58880/60000 (98%)]      Loss: 0.128815
Traceback (most recent call last):
  File "/home/intern/.local/lib/python3.8/site-packages/adaptdl/utils.py", line 27, in wrapper
    return function(*args, **kwargs)
  File "/home/intern/.local/lib/python3.8/site-packages/adaptdl/torch/parallel.py", line 144, in _final_callback
    profile_sync_time(self._sync_start.elapsed_time(sync_end) / 1e3)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/cuda/streams.py", line 173, in elapsed_time
    return super(Event, self).elapsed_time(end_event)
RuntimeError: CUDA error: invalid resource handle
Traceback (most recent call last):
  File "mnist_step_5.py", line 144, in <module>
    main()
  File "mnist_step_5.py", line 135, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "mnist_step_5.py", line 46, in train
    loss.backward()
  File "/home/intern/.local/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/intern/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError
```

### Environment

OS: Ubuntu 16.04.6

Python Version: Python 3.8.1
torch Version: 1.6.0+cu101

NVIDIA-SMI: 418.56
Driver Version: 418.56
CUDA Version: 10.1
Using 4GPUs

**Comment by aurickq** [comment]
Might be the same cause as https://github.com/petuum/adaptdl/issues/93?
