### ISSUE TITLE
Fail to Local Training

### ISSUE THREAD

**Issue by gaow0007** [petuum/adaptdl#93]
PyTorch version : 1.6.0+cu101
Experimental Scripts: https://github.com/petuum/adaptdl/blob/master/tutorial/mnist_step_5.py
Command: 
```
# step 1
python3 -m pip install adaptdl
#  step 2
python -u minist_step_5.py
```

Error Message:
```
INFO:adaptdl.reducer:rank 0 connecting to 0.0.0.0 on port 35479
INFO:adaptdl.reducer:Master waiting for connections on 0
INFO:adaptdl.torch:Initializing torch.distributed using tcp://0.0.0.0:21129?rank=0&world_size=1
INFO:adaptdl.torch:torch.distributed initialized
/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/nn/parallel/distributed.py:364: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES. 
  "Single-Process Multi-GPU is not the recommended mode for "
INFO:adaptdl.torch.epoch:starting at epoch 0
Train Epoch: 0 [0/60000 (0%)]   Loss: 2.321594
Traceback (most recent call last):
  File "mnist_step_5.py", line 144, in <module>
    main()
  File "mnist_step_5.py", line 135, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "mnist_step_5.py", line 46, in train
    loss.backward()
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError
```

**Comment by aurickq** [comment]
Thanks for the bug report! It looks like I'm unable to reproduce the error... Could you say a bit more about your local environment (what OS, number and model of GPUs, etc.)?

**Comment by gaow0007** [comment]
OS Environment:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Python Version:
```
Python 3.6.13 :: Anaconda, Inc.
```

GPU environment 

```
NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1
Product Name                    : Tesla V100-PCIE-32GB
single GPU 
```
Thanks for your reply. 
Hope this is useful for you.

**Comment by aurickq** [comment]
@gaow0007 would you be able to reproduce this error using the changes to adaptdl from https://github.com/petuum/adaptdl/pull/94? It adds better error reporting for the pytorch backward hooks and should help show the actual source of your error.

**Comment by gaow0007** [comment]
Thanks a lot! The bug is from that multi shares the same GPUs.  I try another free GPU and it works. 

```
/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/nn/parallel/distributed.py:364: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES. 
  "Single-Process Multi-GPU is not the recommended mode for "
INFO:adaptdl.torch.epoch:starting at epoch 0
Train Epoch: 0 [0/60000 (0%)]   Loss: 2.321594
Train Epoch: 0 [640/60000 (1%)] Loss: 1.213756
Train Epoch: 0 [1280/60000 (2%)]        Loss: 1.266023
Train Epoch: 0 [1920/60000 (3%)]        Loss: 0.591474
Train Epoch: 0 [2560/60000 (4%)]        Loss: 0.518585
Train Epoch: 0 [3200/60000 (5%)]        Loss: 0.475598
Traceback (most recent call last):
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/adaptdl/utils.py", line 27, in wrapper
    return function(*args, **kwargs)
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/adaptdl/torch/parallel.py", line 133, in _final_callback
    profile_sync_time(self._sync_start.elapsed_time(sync_end) / 1e3)
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/cuda/streams.py", line 173, in elapsed_time
    return super(Event, self).elapsed_time(end_event)
RuntimeError: CUDA error: invalid resource handle
Traceback (most recent call last):
  File "mnist_step_5.py", line 144, in <module>
    main()
  File "mnist_step_5.py", line 135, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "mnist_step_5.py", line 46, in train
    loss.backward()
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre/wgao/miniconda3/envs/adapt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError
```
